// --- CONFIGURATION DE L'EXPOSITION ---
export const EXHIBITION_CONFIG = {
  title: "Déséquilibre",
  subtitle: "Une exploration immersive",
  introText: `Bienvenue dans cette exposition virtuelle explorant le concept du déséquilibre 
à travers trois prismes : le Cosmos, le Corps et l'Esprit. 
Naviguez librement dans cet espace et découvrez les œuvres qui questionnent 
notre rapport à l'instabilité, au changement et à la transformation.

Contrôles : ZQSD ou WASD pour se déplacer, souris pour regarder autour.
Cliquez sur les œuvres pour en savoir plus.`
};

// --- Configuration des salles ---
export const ROOMS_CONFIG = {
  room0: {
    id: 'room0',
    name: 'Hall - Déséquilibre',
    description: `Le déséquilibre est la perte ou l’absence d’un “équilibre” : un manque d’harmonie, de proportions, de concordance. Le “déséquilibré” serait alors celui qui est dans un état de déséquilibre, se manifestant par des changements, des basculements d’un état à un autre, par une déviation du comportement “normal” imposé par la société. 

Ainsi le déséquilibre est peut-être ce qui définit le mieux l’art. L’art comme art de l’informe (Bataille), de la chute, du basculement. Mais comment définir ce qui relève du déséquilibre et de ce qui ne l’est pas ? 

“L’équilibre suggère la mesure, le juste milieu, l’idéal classique des proportions respectées et des limites tenues. Là, rien ne bouge ni ne déborde. Calme plat. “ Evelyne Grosam. 

Le déséquilibre serait-il alors tout ce qui bouge, qui perturbe, qui brise cette harmonie parfaite ?  

Pourtant équilibre et déséquilibre n’ont de sens qu’ensemble. Comme le Bien et le Mal, le succès et l’échec, l’harmonie et le chaos, l’un ne peut pas vivre sans l’autre. Ceux qui n’ont ni besoin de point fixe ni de stabilité, Nietzsche les appelle les danseurs de corde. Ainsi le funambule est peut-être la figure par excellence du déséquilibre : celui qui traverse la corde tendue au-dessus de l’abîme, c’est-à-dire la pensée de l'Éternel Retour avec le suprême danger : la chute. 

Représenter le déséquilibre serait alors représenter la répartition inégale des forces entre tension et détente, fragilité et paradoxale résistance. Dans cette exposition nous avons essayé de proposer un voyage dans la pensée du déséquilibre.  

Georges Bataille en 1929 : « l’informe consiste à déclasser, au double sens de rabaisser, de mettre du désordre dans toute taxinomie, pour annuler les oppositions sur quoi se fonde la pensée logique et catégorielle. »
`,
    color: '#1a1a2e',
    accentColor: '#4a4a6a',
    position: { x: 0, y: 0, z: 0 },
    ambientSound: 'ambient_hall'
  },
  room1: {
    id: 'room1',
    name: 'Cosmos',
    description: `Le cosmos nous rappelle notre place infinitésimale dans l'univers...`,
    color: '#3a2860',
    accentColor: '#9d4edd',
    subthemes: [
      { name: "Harmonie du cosmos", color: "#ff6b35" },
      { name: "Déséquilibre du monde naturel", color: "#4ecdc4" },
      { name: "Déséquilibre dans la représentation du monde", color: "#7b2cbf" }
    ],
    position: { x: -50, y: 0, z: 0 },
    ambientSound: 'ambient_cosmos',
    pattern: 'stars'
  },
  room2: {
    id: 'room2',
    name: 'Corps',
    description: `La salle précédente a commencé notre pensée du déséquilibre en explorant le déséquilibre au sein de mondes naturels et de ses représentations. L’être humain, être faisant partie d’un monde naturel, est lui aussi sujet au déséquilibre, qui s’exprime de différentes manières, mais notamment au travers de son corps. 
    
    Si l’on pense vraiment au corps en tant que tel, il n’est pas possible d’en tracer les contours. Il y a des réflexions sur la systématicité du corps, il y a des valeurs qui codent le corps, mais le corps en tant que tel, ne peut être pensé et, quant à moi, ne ne peux certainement pas l’approcher.” - Gayatri Chakravorty Spivak, “En un mot”, entretien avec Ellen Rooney.

Le corps est une unité et est porteur d’une identité. Les changements du corps résultent de de ceux de l’esprit. Ainsi les déséquilibres du monde se retrouvent dans les corps. On pense aux corps traumatisé, chassés, martyrisés. Si l’humain est celui qui déséquilibre l’harmonie du monde et sa nature, marcher sur Terre ne serait -il pas alors la première forme de déséquilibre ?  

Comment matérialiser le déséquilibre dans le corps ? Comment se l'approprier?  Faut-il toujours trouver un point d’appui ? 

Explorer le déséquilibre dans les corps humains c’est explorer comment le corps subit ce déséquilibre, mais aussi comment il se l’approprie dans le mouvement volontairement déséquilibré, mouvement qui peut être dansé, sculpté ou peint. 
`,
    color: '#502020',
    accentColor: '#ff4444',
    subthemes: [
      { name: 'A- Déséquilibre du corps dans l’espace', color: '#e63946' },
      { name: 'B- Appropriation du déséquilibre : la danse', color: '#f4a261' },
    ],
    position: { x: 50, y: 0, z: 0 },
    ambientSound: 'ambient_body',
    pattern: 'organic'
  },
  room3: {
    id: 'room3',
    name: 'Esprit',
    description: `“Si le déséquilibre humain se traduit par le corps en premier, il peut aussi s’exprimer plus subtilement dans les esprits. « Ne devient pas fou qui veut » - Jacques Lacan 

Dans les conversations banales, on entend parfois qualifier certains individus légèrement désaxés de « déséquilibrés », s’ils ne semblent pas rentrer dans les normes de la société. Être déséquilibré, au sens large d’un trouble de l’équilibre mental supposé être la norme, signifie une catégorie déterminée en suivant cette vision.

Quelles sont les formes du « déséquilibre » mental ? Elles sont multiples et différentes, aussi multiples et différentes que les individus qui les composent. Le fou, figure aussi de l’artiste, a une vision décalée du monde et une manière différente de le comprendre. Car il est en marge, son identité peut aussi se dédoubler ou se multiplier. 

Ainsi, aborder une rupture dans l’équilibre mental conduit aussi à s’interroger sur les normes de la société, sur ce qui est considéré « normal ». Alors, déséquilibré peut devenir synonyme de autre, différent, invisibilisé et représenter le déséquilibre de l’esprit conduit à représenter des cultures invisibilisées, à multiplier les points de vue et les identités. 

Mais, esprit ne peut pas être seulement entendu au singulier. Qu’en est-il des sociétés qui prennent contact avec les esprits, que ce soit ceux des ancêtres ou ceux de la nature ? Il en découle une multiplication des identités et des points de vue, des manières autres de voir et percevoir le monde. 

`,
    color: '#203850',
    accentColor: '#4cc9f0',
    subthemes: [
      { name: 'Perturbation de la vision “normale” du monde', color: '#a8dadc' },
      { name: 'Multiplication des points de vue et identités', color: '#457b9d' },
      { name: 'Esprit et esprits', color: '#1d3557' }
    ],
    position: { x: 0, y: 0, z: -50 },
    ambientSound: 'ambient_mind',
    pattern: 'abstract'
  }
};


// --- Œuvres de l'exposition ---
export const ARTWORKS = {
  room0: [
    {
      id: 'art0_1',
      type: 'painting',
      title: 'Estampe pour le série Los Disparates',
      artist: 'Francisco de Goya',
      year: '1877',
      descriptionSlides: [
        "La série de gravures réalisée par Goya, Los disparates (les disparates) met en lumière la figure du funambule. Personnage qui tient en équilibre, le funambule est ici dédoublé : le cheval et la femme. Le mot disparate est un mot du déséquilibre car lui-même est instable dans la langue française et oscille entre le et la. Ce “défaut d'harmonie”, de contraste, de dissemblance choquante est l’art du déséquilibre.",
        "Au premier plan, une jeune femme funambule se tient debout sur un cheval blanc lui-même en équilibre sur une corde tendue. En arrière-plan, on distingue un amas de visages, une foule. Est-ce un rêve, une tromperie ? Le cheval est-il en équilibre sur la corde ou la corde est-elle au sol ? Certains rient, certains ferment les yeux, l’assemblage de ces deux plans laisse les spectateurs songeurs.",
        
      ],
      dimensions: '36 x 25cm',
      position: { x: 0, y: 3, z: 9.5 },
      rotation: { x: 0, y: Math.PI, z: 0 },
      medium: 'eau-forte, aquatinte et pointe sèche',
      scale: { x: 2.5, y: 2.5, z: 1 },
      image: '/oeuvres/goya.png',
      location: 'BNF, Paris',
      inventoryNumber: 'RF 1937-45 (R0-001)', // Exemple de numéro unique
    },
  ],
    room1: [
      // ---------------- Zone 1 : Harmonie du cosmos ----------------
      { 
        id: 'art1_1', 
        type: 'painting', 
        title: 'Mandala de Buddhakapaladhara', 
        artist: 'Peinture, Détrempe sur toile,', 
        year: '',
        descriptionSlides: ['Le Mandala « cercle » ou « objet en forme de disque » en sanskrit, est une représentation graphique de l’univers  et aussi un guide pour de nombreuses pratiques comme la méditation. Dans l’hindouisme et le bouddhisme, on croit qu’en pénétrant dans le mandala et en se rapprochant de son centre, on est guidé dans le cheminement cosmique qui vise à transformer l’univers de la douleur en un univers de joie et de bien-être.',
          
          'Dans un cheminement allant de l’extérieur vers l’intérieur, on pénètre dans le mandala par l’Est, au bas de la peinture. L’adepte poursuit son parcours dans le sens des aiguilles d’une montre au sein des enceintes concentriques correspondant chacune à un niveau de spiritualité toujours plus élevé. Peuplées de nombreux personnages (aspects secondaires de la divinité principale, membres de son entourage, déités protectrices et gardiennes), ces enceintes conduisent au centre de la composition où se tient la divinité souveraine du mandala.'], 
        medium: 'écorce et pigments noir, rouge, blanc, jaune', 
        dimensions: '72 x 83 cm',
        position: { x: -60, y: 4, z: -4 }, 
        rotation: { x: 0, y: Math.PI / 2, z: 0 }, 
        subtheme: 0, 
        image: 'oeuvres/cosmos/Equilibre/Buddhakapaladhara.jpg',
        location: 'Musée Guimet',
        inventoryNumber: 'MA 12487',
      },
      { 
        id: 'art1_2', 
        type: 'painting', 
        title: 'Rêve de la carotte sauvage', 
        artist: 'Paddy Jupurrurla Nelson', 
        year: '1991',
        description: 'Paddy Jupurrurla Nelson est un artiste de la communauté Yuendumu. Il est l’un des premiers hommes Yuendumu à peindre à l’acrylique. Dans cette peinture, il exprime un sujet mythologique de la cosmogonie aborigène, le « Temps du rêve ». Le « Temps du rêve » est une période mythique durant laquelle la vie a été créée. L’utilisation de l’ocre rouge, symbole du sang et de la vie, est particulièrement significative dans ces peintures, notamment pour évoquer la présence des êtres ancestraux qui sont les architectes du monde. ', 
        medium: 'acrylique sur toile', 
        dimensions: '76 x 92 cm',
        position: { x: -60, y: 8, z: -6 }, 
        rotation: { x: 0, y: Math.PI / 2, z: 0 }, 
        subtheme: 0, 
        image: 'oeuvres/cosmos/Equilibre/carrote_sauvage.png',
        location: 'musée du quai Branly, Paris',
        inventoryNumber: '72.1991.0.59',
      },
      { 
        id: 'art1_3', 
        type: 'painting', 
        title: 'La Mecque au centre du monde', 
        artist: 'Alî ibn Aḥmad ibn Moḥammad al-Scharqî', 
        year: '1551',
        description: 'carte centrée autour de  la pierre noire désignant la qibla', 
        medium: 'Manuscrit, 8 feuillets, cartes en couleurs,', 
        dimensions: ' 20 x 25 cm',
        position: { x: -60, y: 9 , z: 2 }, 
        rotation: { x: 0, y: Math.PI / 2, z: 0 }, 
        subtheme: 0, 
        image: 'oeuvres/cosmos/Equilibre/Orbis_Terrarum.jpg',
        location: 'BnF, département des Manuscrits',
        inventoryNumber: 'Arabe 2278 fol. 2v',
      },
      { 
        id: 'art1_4', 
        type: 'painting', 
        title: 'Peinture sur écorce', 
        artist: 'Liwukan Bukulatipi', 
        year: '1996',
        descriptionSlides: ["Cartel Enfant : Approche-toi. Arrives-tu à voir de quel matériau est fait le support de cette peinture ? C’est fait en écorce d'arbre ! La peinture sur écorce est un art traditionnel de certains peuples qui vivent au nord de l’Australie. Ces peintures étaient notamment réalisées pour des cérémonies. Regarde aussi les couleurs !", 
          "Il y a beaucoup de rouge parce que c’est la couleur associée au sang et à la vie, et on la retrouve beaucoup dans les peintures traditionnelles des peuples australiens. Mais dis-moi, est-ce que tu voudrais essayer de peindre sur une écorce d’arbre ?"],
        hasChildLabel: true,
        medium: 'écorce et pigments noir, rouge, blanc, jaune', 
        dimensions: '62 x 88 cm',
        position: { x: -60, y: 4, z: 3 }, 
        rotation: { x: 0, y: Math.PI / 2, z: 0 }, 
        subtheme: 0, 
        image: 'oeuvres/cosmos/Equilibre/peinture_sur_ecorce.png',
        location: 'musée du quai Branly, Paris',
        inventoryNumber: '72. 1996.6.1',
      },
  
      // ---------------- Zone 2 : Déséquilibre du monde naturel ----------------
      { 
        id: 'art1_5', 
        type: 'painting', 
        title: "Adam et Eve, La Chute de l'homme", 
        artist: 'Albrecht Dürer', 
        year: '1504',
        descriptionSlides: ['Dans la genèse, Adam et Eve brise l’équilibre du jardin d’Eden. Donc la condition humaine déséquilibre la Terre, création parfaite de Dieu.' ,
"L’harmonie serait alors en lien avec le bien et le désordre avec le mal. Autrement dit, le paradis = le bien , l’harmonie tandis que les enfers = le mal, le diable, le déséquilibre. "]
, 
        medium: "Burin. Signé et daté sur une tablette suspendue à la branche que tient Adam : ALBERT / DVRER / NORICVS / FACIEBAT / monogramme de l'artiste, 1504", 
        dimensions: '20 x 26 cm',
        position: { x: -57, y: 5.5, z: 9 }, 
        rotation: { x: 0, y: Math.PI, z: 0 }, 
        subtheme: 1, 
        image: 'oeuvres/cosmos/Desequilibre naturel/adam_eve.png',
        location: 'Musée du Louvre, Paris ',
        inventoryNumber: 'vol.1, p.28',
      },
      { 
        id: 'art1_6', 
        type: 'painting', 
        title: 'Bateaux sur une mer agitée près d’une côte rocheuse', 
        artist: 'Anonyme', 
        year: '1600',
        description: '', 
        medium: 'toile', 
        dimensions: '81 x 65 cm',
        position: { x: -40, y: 6, z: -4 }, 
        rotation: { x: 0, y: -Math.PI / 2, z: 0 }, 
        subtheme: 1, 
        image: 'oeuvres/cosmos/Desequilibre naturel/cote_rocheuse.png',
        location: 'musée du Louvre, Paris',
        inventoryNumber: 'MNR 645',
      },
      { 
        id: 'art1_7', 
        type: 'painting', 
        title: 'Incendie du Kent', 
        artist: 'Théodore Gudin', 
        year: '1825',
        description: 'Premier artiste nommé peintre de la Marine royale, Théodore Gudin a 26 ans quand il présente cette composition en 1828. Profondément marqué par la noyade de son frère, Gudin exprime dans cette composition grandiose la puissance de la mer, qui semble omniprésente. La composition en diagonale exprime le déséquilibre des forces dans ce tableau : d’un côté, le navire sur le point de sombrer et les quelques survivants qui s’accrochent à la vie sur le canot. De l’autre, une mer sombre et déchaînée qui veut tout emporter sur son passage. L’équilibre est rompu dans ce tableau, entre monde naturel et monde humain. ', 
        medium: 'huile sur toile', 
        dimensions: '417 x 259 cm',
        position: { x: -48, y: 7, z: 9 }, 
        rotation: { x: 0, y: Math.PI, z: 0 }, 
        subtheme: 1, 
        image: 'oeuvres/cosmos/Desequilibre naturel/kent.png',
        location: 'musée national de la Marine, Paris',
        inventoryNumber: '9 OA 34D'
,
      },
      { 
        id: 'art1_8', 
        type: 'painting', 
        title: 'L’éruption du Vésuve; vue en hauteur', 
        artist: 'Pierre Jacques Volaire', 
        year: '1757',
        descriptionSlides: ["Cartel Enfant : Connais-tu l’histoire de la ville de Pompéi et de son voisin le volcan Vésuve? En 79 après JC, le Vésuve entre en éruption, ensevelissant la ville romaine de Pompéi sous les cendres. C’est ce qui est montré sur la peinture, tu vois le volcan ? Regarde de plus près, en bas, il y a des gens qui essaient de s'enfuir. Beaucoup d’habitants de Pompéi n’ont pas survécu à l'éruption du Vésuve. ",
          "Tu dois te demander mais quel est le rapport avec le déséquilibre, le thème de notre exposition ? Et bien cette peinture représente une force de la nature qui crée des problèmes dans la vie des habitants de Pompéi. On peut dire que la nature déséquilibre la vie que les gens avaient à Pompéi. ",
        ],
        hasChildLabel: true,
        medium: 'huile sur toile', 
        dimensions: '110 x 166 cm',
        position: { x: -40, y: 8, z: 3 }, 
        rotation: { x: 0, y: -Math.PI / 2, z: 0 }, 
        subtheme: 1, 
        image: 'oeuvres/cosmos/Desequilibre naturel/vesuve.png',
        location: 'musée du Louvre, Paris',
        inventoryNumber: 'INV 8489 bis et  MR 2703',
      },
      {
        id: 'art2_9',
        type: 'glb',
        url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/chaudiere_enfer.glb',
        title: "Adam et Eve et la chaudière de l'Enfer",
        artist: 'Inconnu',
        year: 'vers 1230',
        description: '',
        medium: 'pierre calcaire traces de polychromie',
        dimensions: '82 x 52 x 46cm',
        position: { x: -41, y: 0.5, z: 5 },
        rotation: { x: 0.1, y: - Math.PI/2, z: 0.15 },
        subtheme: 0,
        image : 'oeuvres/cosmos/Desequilibre naturel/chaudiere_enfer.png',
        location: 'Musée du Louvre, Lens',
        inventoryNumber: 'RF 991',
      },
      {
        id: 'art2_10_glb',
        type: 'glb',
        url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/torse.glb',
        title: 'Torse de la Ville détruite',
        artist: 'Ossip Zadkine',
        year: '1951 - 1963',
        descriptionSlides: ["Zadkine découvre en juin 1947, la ville de  Rotterdam rasée par les bombardements allemands en mai 1940. Dans ses souvenirs il raconte la violence des impressions qu’il ressentit alors : « L’image de la ville et des rues annihilées de Rotterdam me poursuivait. Rentré à Paris, je modelais en terre un projet de statue qui tentait d’exprimer le désarroi et l’horreur mêlés ». La « première esquisse pour un monument à une ville détruite », fut brisée lors d’un transport. Une nouvelle version d’un « projet de monument pour une ville bombardée » vit le jour en 1947. ",
"Les lignes brisées, les mouvement de torsion, les vides et plein confèrent au sentiment tragique de cette oeuvre. Le déséquilibre est alors un moyen d'exprimer la douleur humaine.  Avec cette oeuvre, Zadkine atteint le but suprême qu’il s’était fixé au moyen de son art : « engendrer l’émotion chez celui qui le regarde, exhaler un quelque chose qui subjugue le spectateur, qui lui entrouvre un chemin insoupçonné au sein de sa propre âme ».",
],
        medium: 'Bronze, épreuve 2/5, Susse fondeur',
        dimensions: '127 x 57 x 56cm',
        position: { x: -59, y: 2, z: 7 },
        rotation: { x: 0, y: Math.PI/2, z: 0 },
        subtheme: 0,
        image : 'oeuvres/cosmos/Desequilibre naturel/torse.png',
        location: 'Paris, Musée Zadkine',
        inventoryNumber: 'MZS 250',

      },
      // ---------------- Zone 3 : Déséquilibre dans la représentation ----------------
      {
        id: 'art3_15',
        type: 'painting',
        title: 'Le bal Bullier',
        artist: 'Sonia Delaunay',
        year: '1913',
        description: '',
        medium: 'huile sur toile à matelas',
        dimensions: ' 390 x 97 cm',
        position: { x: -51, y: 9, z: -9 },
        rotation: { x: 0, y: 0, z: 0 },
        image: 'oeuvres/cosmos/Desequilibre represente/bullier.jpg',
        subtheme: 1,
        location: 'Centre pompidou', // Valeur spécifique
        inventoryNumber: 'AM 3307 P',
      },
      {
        id: 'art3_16',
        type: 'painting',
        title: "Les Usines du Rio-Tinto à L'Estaque",
        artist: 'Georges Braque',
        year: 'automne 1910',
        description: 'Cartel Enfant : Regarde bien cette peinture. Tu ne trouves pas qu’elle est un peu bizarre ? Bien vu, on ne peut pas reconnaître ce qu’elle représente ! C’est ce qu’on appelle l’art abstrait. Et regarde tous les petits rectangles qu’il y a dans la peinture : c’est parce que c’est le peintre appartient au mouvement du cubisme. Lui et d’autres artistes veulent prendre les choses et les voir différemment, en donnant beaucoup de place aux formes géométriques. Viens par là, j’ai un défi pour toi : peux-tu compter le nombre de rectangles sur ce dessin ?',
        hasChildLabel: true,
        medium: 'Peinture Huile sur toile',
        dimensions: ' 54 x 65 cm',
        position: { x: -51, y: 3, z: -9 },
        rotation: { x: 0, y: 0, z: 0 },
        image: 'oeuvres/cosmos/Desequilibre represente/rio_tinto.jpg',
        subtheme: 1,
        location: 'Musée National d’Art Moderne, Centre Pompidou',
        inventoryNumber: 'AM 3973 P',
      },
      {
        id: 'art3_17',
        type: 'painting',
        title: 'Bouteille de Bass et carte de visite',
        artist: 'Pablo Picasso',
        year: 'printemps 1914',
        description: '',
        medium: 'Mine graphite et papiers collés sur papier,',
        dimensions: ' 30 x 24 cm',
        position: { x: -45, y: 2, z: -9 },
        rotation: { x: 0, y: 0, z: 0 },
        image: 'oeuvres/cosmos/Desequilibre represente/bass.png',
        subtheme: 1,
        location: 'Centre Pompidou, Paris',
        inventoryNumber: 'AM 1984-628',
      },
      {
        id: 'art3_18',
        type: 'glb',
        url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/bouteille.glb',
        title: 'Bouteille et verre',
        artist: 'Henri Laurens',
        year: '1918',
        description: '',
        medium: 'Bois et tôle de fer polychromes',
        dimensions: '62 x 34 x 21cm',
        position: { x: -53.5, y: 0.5, z: - 6},
        rotation: { x: 0, y: Math.PI/2, z: 0 },
        subtheme: 2,
        image : 'oeuvres/cosmos/Desequilibre represente/bouteille.jpg',
        location: 'Centre Pompidou, Paris',
        inventoryNumber: 'AM 1984-569',
      }
    ]
  

  ,
  room2: [
    {
      id: 'art2_1',
      type: 'painting',
      title: 'Autoportrait au coude droit',
      artist: 'Egon Schiele',
      year: '1914',
      description: '',
      medium: 'gouache, papier, crayon',
      dimensions: '31 x 48cm',
      position: { x: 43, y: 5, z: -9 },
      rotation: { x: 0, y: 0, z: 0 },
      image: 'oeuvres/corps/espace/coude.jpg',
      subtheme: 0,
      location: 'collection privée',
      inventoryNumber: '',
    },
    {
      id: 'art2_2',
      type: 'painting',
      title: 'Selbstporträt mit blauen Fleck',
      artist: 'Georg Baselitz',
      year: '1996',
      description: '',
      medium: 'peinture à l’huile',
      dimensions: '205 x 290cm',
      position: { x: 49, y: 5, z: -9 },
      rotation: { x: 0, y: 0, z: 0 },
      image: 'public/oeuvres/corps/espace/Selbstporträt.png',
      subtheme: 0,
      location: 'Musée d’art moderne, Paris',
      inventoryNumber: 'AMVP 2781',
    },
    {
      id: 'art2_10_glb', // ID corrigé pour l'unicité
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/daniel.glb',
      title: 'Daniel dans la fosse aux lions',
      artist: 'inconnu',
      year: '500 / 1125',
      description: '',
      medium: 'marbre de Carrare',
      dimensions: '50 x 53 x 51 cm',
      position: { x: 57, y: 2, z: -9.5 },
      rotation: { x: 0.1, y: 0, z: 0.15 },
      subtheme: 0,
      location: 'Musée du Louvre, Paris',
      inventoryNumber: 'RF 457',
      image : 'oeuvres/corps/espace/daniel.jpg'
    },
    
    {
      id: 'art2_3',
      type: 'painting',
      title: 'Deux danseurs',
      artist: 'Henri Matisse',
      year: '1937 - 1938',
      description: '',
      medium: 'Dessin, Papiers gouachés, découpés et punaisés, et mine graphite sur carton collé sur châssis',
      dimensions: '64 x 80cm',
      position: { x: 59, y: 2.5, z: 7 },
      rotation: { x: 0, y: -Math.PI / 2, z: 0 },
      image: 'oeuvres/corps/la dance/matisse.png',
      subtheme: 1,
      location: 'Centre Pompidou, Paris',
      inventoryNumber: 'AM 1991-280',
    },
    {
      id: 'art2_4',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/venus.glb',
      title: 'La vénus à tiroirs',
      artist: 'Salvador Dali',
      year: '1936',
      descriptionSlides: ["Cette sculpture en plâtre créée par Dalí en 1936 est inspirée de la Vénus de Milo du Musée du Louvre. Le contrapposto, l’absence de bras et l’ajout de tiroir l'élève au statut de figure déséquilibré. Cette icône de l’Antiquité a retenu l’attention de l’artiste dès son plus jeune âge. ",
        "Dans La vie secrète de Salvador Dalí, il rapporte qu’enfant, il avait réalisé une copie en terre glaise de cette œuvre et qu’il avait retiré de ce premier essai sculptural « une véritable satisfaction érotique ». ",
        "Plus tard, dans une interview donnée à la revue Playboy en 1964, Dalí explique que « l’ajout des tiroirs permet de voir l’intérieur du corps de la Vénus de Milo jusqu’à l’âme : ainsi, Dalí crée une apparition freudienne et chrétienne dans la civilisation grecque ». ",
      ],
      medium: 'Plâtre peint, poignées métalliques et pompons en vison',
      dimensions: '98 x 32 x 34cm',
      position: { x: 57, y: 7, z: -9.5 },
      rotation: { x: 0.1, y: 0, z: 0.15 },
      subtheme: 0,
      image: 'oeuvres/corps/espace/venus.jpg',
      location: 'Galerie du Dragon, Paris',
      inventoryNumber: 'Num. cat. OE 24',
    },
    {
      id: 'art2_5',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/daphne.glb',
      title: 'Daphné (poursuivie par Apollon),',
      artist: 'Guillaume Coustou',
      year: '1713/1715',
      description: 'Cartel Enfant : Regarde la femme devant toi. Arrives-tu à comprendre son expression ? Bien vu ! Elle a peur parce qu’elle se fait poursuivre par le dieu Apollon, qui n’est pas représenté. Dans la mythologie grecque, Daphné est une nymphe, un esprit de la nature. Apollon, le dieu du Soleil et de la musique, tombe fou amoureux d’elle mais elle le rejette. Il continue pourtant de la poursuivre et désespérée, elle demande à son père de la changer en arbre. On ne voit pas cette partie de l’histoire sur la statue, mais tu peux voir Daphné en train de fuir. Mais dis-moi, est-ce que tu aurais peur à la place de Daphné ?',
      hasChildLabel: true,
      medium: 'marbre',
      dimensions: '132 x 135 x 65cm',
      position: { x: 59, y: 0, z: 0 },
      rotation: { x: 0, y: -Math.PI/2, z: 0 },
      subtheme: 0,
      location: 'musée du Louvre, Paris',
      inventoryNumber: 'MR 1807',
      image: 'oeuvres/corps/espace/daphne.png'
    },
    {
      id: 'art2_6_glb',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/statuette.glb',
      title: 'Statuette',
      artist: 'Inconnu',
      year: 'Ie s. ap. J.-C.',
      description: '',
      medium: 'bronze et or',
      dimensions: '22 x 9 x 7cm',
      position: { x: 50, y: 0.7, z: -3 },
      rotation: { x: 0.1, y: 0, z: 0.15 },
      subtheme: 0,
      location: 'musée du Louvre, Paris',
      inventoryNumber: 'MND 2333, Br 4417.1',
      image: 'oeuvres/corps/espace/statuette.png',
    },

    {
      id: 'art2_7_glb',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/zoomorphe.glb',
      title: 'Figurine zoomorphe',
      artist: 'Inconnu',
      year: 'XI-XVIIIe siècle',
      description: '',
      medium: 'alliage cuivreux',
      dimensions: '20 x 10 x 10cm',
      position: { x: 43, y: 0.7, z: -6 },
      rotation: { x: 0.1, y: 0, z: 0.15 },
      subtheme: 0,
      location: 'musée du Quai Branly, Paris',
      inventoryNumber: '71.1903.8.3',
      image:'oeuvres/corps/espace/zoomorphe.png'
    },
    {
      id: 'art2_8_glb',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/chavire.glb',
      title: 'Homme qui chavire',
      artist: 'Alberto Giacometti',
      year: '1950',
      descriptionSlides: ["Homme qui chavire. Le titre de l'œuvre exprime bien le côté déséquilibré de la composition. Cet homme filiforme semble prêt à basculer d’un côté, à abandonner l’idée de rester debout : l’inflexion des jambes, les bras qui pendent, la tête légèrement en arrière, tout exprime une impuissance. Le déséquilibre est ici au service de la volonté de l’artiste de mieux appréhender la réalité grâce à l’art.",
        "Selon lui, une sculpture « n'est pas un objet, elle est une interrogation, une question, une réponse, elle ne peut être ni finie ni parfaite ». Ici, la sculpture interroge la fatalité de la condition humaine, toujours prête à basculer d’un côté ou de l’autre. "
      ],
      medium: 'bronze peint',
      dimensions: '60 x 22 x 36cm',
      position: { x: 45, y: 0.7, z: -5 },
      rotation: { x: 0, y: 0, z: 0 },
      subtheme: 0,
      location: 'Fondation Giacometti, Paris',
      inventoryNumber: 'AGD 915',
      image: 'oeuvres/corps/espace/chavire.png'
    },
    {
      id: 'art2_9_glb',
      type: 'glb',
      url: 'oeuvres/corps/diabolo.glb',
      title: 'Le Diabolo',
      artist: 'Germaine Richier',
      year: '1950',
      descriptionSlides: ["Germaine Richier représente un corps jouant au diabolo pour reprendre le titre de l’oeuvre.",
        "Le corps semble pris dans un état de déséquilibre, figé par les pieds ancrés sur un socle. Les fils attirent son corps vers l’arrière, la retenant de basculer. Les forces se compensent. Mais la matérialité laisse  le spectateur perplexe.  Le bronze n’est plus lisse mais devient matière vivante, rendant compte de l’humanité de la sculpture de sa fragilité et de sa sensibilité. Ce matériau noir et dense s’allie à des fils de fer légers et fins, déséquilibrant l’oeuvre dans son ensemble. L’ombre renforce ce sentiment de déséquilibre.",
      ],
      medium: 'Bronze et fer',
      dimensions: '160 x 49 x 60cm',
      position: { x: 52, y: 0.7, z: 8 },
      rotation: { x: 0.1, y: Math.PI, z: 0.15 },
      subtheme: 0,
      location: 'Musée National d’Art Moderne, Centre pompidou, Paris',
      inventoryNumber: 'AM 949 S',
      image: 'oeuvres/corps/unknown.png'
    },
    
    {
      id: 'art2_7_pint',
      type: 'painting',
      title: 'Chronophotographie d’un escrimeur',
      artist: 'Georges Demenÿ',
      year: '1902',
      description: '',
      medium: "Tirage papier d'après négatif sur plaque de verre",
      dimensions: '12 x 9 cm',
      position: { x: 41, y: 2.5, z: 9 },
      rotation: { x: 0, y: Math.PI, z: 0 },
      image: 'oeuvres/corps/la dance/Chronophotographie.jpg',
      subtheme: 0,
      location: 'École de Joinville,  INSEP, Paris, ',
      inventoryNumber: '',
    },
    {
      id: 'art2_8_pint',
      type: 'painting',
      title: 'Helen Tamiris',
      artist: 'Man Ray',
      year: 'vers 1930',
      description: '',
      medium: 'À définir',
      dimensions: '7 x 11 cm',
      position: { x: 44, y: 2, z: 9 },
      rotation: { x: 0, y: Math.PI, z: 0 },
      image: 'oeuvres/corps/la dance/helen.png',
      subtheme: 0,
      location: 'Centre Pompidou, Paris',
      inventoryNumber: 'AM 1994-394 (3206)',
    },
    {
      id: 'art2_9_vid',
      type: 'youtube',
      title: 'Café Müller, Tanztheater Wuppertal',
      artist: 'Pina Bausch, Henri Purcell',
      year: '1978',
      descriptionSlides: ["Pina Bausch s’interresse au rapport femme homme et au conflit de communication au déséquilibre du couple. La scène, recouverte de chaises de bistro,  est un espace que les danseurs doivent moduler pour pouvoir y circuler. Le corps du danseur est en perpétuel contact avec ce qui l'entoure : les chaises, les murs, le sol , cherchant des points d'appuis.",
        "Les contacts sont violents  et les corps douloureux, transformés. Les danseurs tentent de se frayer un passage dans le désordre perpétuel, certains évoluent même durant l'ensemble de l'œuvre les yeux fermés. Ici, la femme ne cesse de chuter et de se relever comme pour retrouver l’équilibre perdu. Elle ne cesse de changer d'état, de basculer. ",
      ],
      medium: 'Vidéo YouTube',
      dimensions: '150 x 100 cm',
      position: { x: 48, y: 6, z: 9 },
      rotation: { x: 0, y: Math.PI, z: 0 },
      youtubeId: 'Y_0GvlL4s9o',
      subtheme: 1,
      location: '',
      inventoryNumber: '',
    },
    {
      id: 'art2_10_pint',
      type: 'painting',
      title: '[Corps 9]',
      artist: 'À venir',
      year: '2024',
      description: '',
      medium: 'À définir',
      dimensions: '120 x 90 cm',
      position: { x: 55, y: 2.5, z: 9 },
      rotation: { x: 0, y: Math.PI, z: 0 },
      image: 'oeuvres/corps/dance/Chronophotographie.jpg/',
      subtheme: 2,
      location: 'Collection Particulière',
      inventoryNumber: 'EXP-D-0029',
    },

    {
      id: 'art2_11_glb',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/valse.glb',
      title: 'La Valse ou les Valseurs',
      artist: 'Camille Claudel',
      year: 'vers 1893',
      descriptionSlides: ["Cette œuvre représente un couple de danseurs en mouvement autour d’un axe oblique. Le mouvement, mis en valeur par le drapé de la jupe de la danseuse, semble pousser les valseurs jusqu’à leur point d’équilibre. Le pied levé du danseur, accompagnant la jupe de sa partenaire, ainsi que la présence de la base rectangulaire renforcent l’impression de déséquilibre générale qui se dégage de l'œuvre, caractéristique des travaux de la sculptrice Camille Claudel.",
        "Le déséquilibre s’exprime aussi dans le contraste entre la musculature du danseur et la sensualité du corps de sa partenaire, évoquant un amour charnel et infini."
      ],
      medium: 'bronze',
      dimensions: '44 x 25 x 25cm',
      position: { x: 56, y: 0.7, z: 8 },
      rotation: { x: 0, y: Math.PI, z: 0 },
      subtheme: 1,
      location: 'Musée Rodin',
      inventoryNumber: 'S.01013',
      image: 'oeuvres/corps/la dance/valse.jpg'
    },
    {
      id: 'art2_12_glb',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/Vajravarahi.glb',
      title: 'Vajravarahi',
      artist: 'Inconnu',
      year: 'XVe siècle',
      descriptionSlides: ["Cartel Enfant : Regarde cette statue. Arrives-tu à deviner ce que la dame fait ? Elle est représentée en position de danse, comme le sont la plupart des autres dakini. Mais qu’est-ce qu’une dakini? Et bien les dakinis sont, dans la religion bouddhiste au Tibet, des entités féminines qui ont plusieurs rôles. Celle représentée ici s’appelle Vajravarahi et est une représentation de la sagesse. ",
        "J’entends une petite voix dans mon oreille qui me souffle ta question. Je suis d’accord, on peut bien se demander le rapport avec le déséquilibre. Essaie de marcher, très lentement. Tu remarques qu’en gardant ta jambe en l’air, tu es déséquilibré à un moment. Et oui, le corps humain est tout le temps déséquilibré dans tous ses mouvements. Mais, quand tu danses, tu peux jouer avec ce déséquilibre, pour en faire ton ami. Allez, maintenant, je veux voir ta plus belle chorégraphie ! ",
      ],
      hasChildLabel: true,
      medium: 'cuivre doré, turquoise, argent,',
      dimensions: '27 x 13 x 12cm',
      position: { x: 42, y: 0.7, z: 7 },
      rotation: { x: 0.1, y: 3, z: 0.15 },
      subtheme: 1,
      location: 'musée Guimet, Paris',
      inventoryNumber: 'MA 13459',
      image: 'oeuvres/corps/la dance/Vajravarahi.png'
    }
  ],
  room3: [
    {
      id: 'art3_1',
      type: 'painting',
      title: 'Trois femmes trois loups',
      artist: 'Eugène Grasset',
      year: 'vers 1892',
      description: 'Sorcières, considérées comme hystérique et folle, chassées et brulées ',
      medium: 'crayon, aquarelle, encre de chine et rehauts d’or',
      dimensions: '40 x 54 cm',
      position: { x: -9, y: 2.5, z: -59 },
      rotation: { x: 0, y: 0, z: 0 },
      image: 'oeuvres/esprit/perturbation/3femme_3loups.jpg',
      subtheme: 0,
      location: 'Musée des Arts décoratifs de Paris',
      inventoryNumber: '',
    },
    {
      id: 'art3_2',
      type: 'painting',
      title: 'Psautier de Jean de Berry',
      artist: 'Jacquemart de Hesdin',
      year: '1386 et 1400',
      description: '',
      medium: 'Enluminures sur parchemin',
      dimensions: '17 x 25 cm',
      position: { x: -9, y: 2, z: -55 },
      rotation: { x: 0, y: Math.PI/2, z: 0 },
      image: 'oeuvres/esprit/perturbation/jacquemart.jpg',
      subtheme: 0,
      location: 'Bibliothèque nationale de France',
      inventoryNumber: 'Fr.13091',
    },
    {
      id: 'art3_3',
      type: 'painting',
      title: 'Que me veux-tu ?',
      artist: 'Claude Cahun',
      year: '1928',
      description: '',
      medium: 'Photographie, tirage gélatino-argentique développé',
      dimensions: '23 x 18 cm',
      position: { x: -9, y: 3, z: -53 },
      rotation: { x: 0, y: Math.PI/2, z: 0 },
      image: 'oeuvres/esprit/perturbation/que_me_veux_tu.png',
      subtheme: 0,
      location: 'Musée d’Art moderne de Paris',
      inventoryNumber: 'AMVP 3338',
    },
    {
      id: 'art4_4',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/table.glb',
      title: 'La table',
      artist: 'Alberto Giacometti',
      year: '1933',
      description: '',
      medium: 'Plâtre',
      dimensions: '148 x 103 x 43cm',
      position: { x: 0, y: 3, z: - 54},
      rotation: { x: 0, y: 0, z: 0 },
      subtheme: 1,
      location: 'Musée d’art Moderne, Paris',
      inventoryNumber: 'AM 960 S',
      image: 'oeuvres/esprit/perturbation/table.jpg',
    },
    {
      id: 'art3_5',
      type: 'painting',
      title: 'Le Saut dans le vide',
      artist: 'Yves Klein',
      year: '1960',
      descriptionSlides: ["Cartel Enfant : Je suis d’accord avec toi, on peut se demander pourquoi il est en train de sauter dans le vide. Cette action paraît étrange, pas vraiment normale. En réalité, ce qu’il est en train de faire te permet de te poser plein de questions ! Qu’est-ce qui est normal pour toi par exemple ? Est-ce que tu n’es pas un peu curieux de savoir ce que ça fait de sauter dans le vide ?",
        "Finalement, on est peut-être un peu tous comme ce monsieur. Alors, la prochaine fois que tu vois quelque chose de bizarre, qui sort de l’ordinaire, pose toi des questions et essaie de comprendre ?"],
      hasChildLabel: true,
      medium: 'Tirage en recto sur PVC 2mm M1, montée sur chassis noir au verso et équipée de 2 anneaux d’accroche',
      dimensions: '50 x 60 cm',
      position: { x: -9, y: 5, z: -52 },
      rotation: { x: 0, y: Math.PI / 2, z: 0 },
      image: 'oeuvres/esprit/perturbation/saut.jpg',
      subtheme: 0,
      location: 'la revue Dimanche en octobre 1960',
      inventoryNumber: '',
    },
    {
      id: 'art3_6',
      type: 'painting',
      title: 'Family Commission With Snake',
      artist: 'Tina Barney',
      year: '2007',
      description: ["Née en 1945, Tina Barney entreprend à la fin des années 1970 de photographier ses proches et amis. Elle s’intéresse particulièrement aux relations entre les générations dans le cadre domestique.",
        "A première vue, ses portraits semblant tenir de l’instantané familial, sont pour la plupart soigneusement mis en scène par l’artiste.  Tina Barney capture des moment d'interactions sous tension relevant du déséquilibre familial ou personnel des sujets.",
      ],
      medium: 'Photographie',
      dimensions: '37 x 28 cm',
      position: { x: -9, y: 6, z: -43 },
      rotation: { x: 0, y: Math.PI / 2, z: 0 },
      image: 'oeuvres/esprit/perturbation/barney.png',
      subtheme: 0,
      location: 'courtesy Kasmin, New York',
      inventoryNumber: '',
    },
    {
      id: 'art3_7',
      type: 'painting',
      title: 'Sans titre',
      artist: 'Joan Miro',
      year: '1973',
      description: '',
      medium: 'encre de Chine gouache et pastel sur Papier',
      dimensions: '58 x 45 cm',
      position: { x: -9, y: 5, z: -48 },
      rotation: { x: 0, y: Math.PI / 2, z: 0 },
      image: 'oeuvres/esprit/perturbation/sans_titre.png',
      subtheme: 1,
      location: 'Centre pompidou, Paris',
      inventoryNumber: 'AM 1980-300',
    },
    {
      id: 'art3_8',
      type: 'painting',
      title: 'Selfportrait',
      artist: 'Francis Bacon',
      year: '1971',
      description: '',
      medium: 'Huile sur toile',
      dimensions: '30 x 35 cm',
      position: { x: -9, y: 2.5, z: -48 },
      rotation: { x: 0, y: Math.PI / 2, z: 0 },
      image: 'oeuvres/esprit/perturbation/bacon.jpg',
      subtheme: 1,
      location: 'Centre Pompidou, Paris',
      inventoryNumber: 'AM 1984-485',
    },
    {
      id: 'art3_9',
      type: 'painting',
      title: 'Portrait [prémonitoire] de Guillaume Apollinaire',
      artist: 'Giorgio de Chirico',
      year: 'printemps 1914',
      descriptionSlides: ["Giorgio De Chirico arrive à Paris en 1911, où il intègre deux ans plus tard le cercle qui se forme autour d’Apollinaire. Dès 1913, le poète admire la production du peintre et la défend dans plusieurs articles. Conscient de la contribution du poète à son succès, De Chirico lui rend hommage en lui offrant ce portrait aux attributs orphiques.",
        "Apollinaire décide d’en utiliser l’image comme frontispice de son premier recueil de calligrammes, Et moi aussi je suis peintre, publié en 1914. Une cible « prémonitoire » tracée sur la tempe de l’ombre représentant le poète de profil indique précisément l’endroit où il sera frappé par un éclat d’obus pendant la guerre, en 1916.",
        "Chirico fait du poète et de l’artiste une figure visionnaire qui permet de voir l’invisible, de voir le futur. Ainsi, il dédouble le poète et mêle portrait antique “équilibrée” et figure de l’ombre “déséquilibrée”. ",
      ],
      medium: 'huile et fusain sur toile',
      dimensions: '65 x 81 cm',
      position: { x: -9, y: 3.5, z: -43 },
      rotation: { x: 0, y: Math.PI / 2, z: 0 },
      image: 'oeuvres/esprit/perturbation/Appolinaire.jpg',
      subtheme: 0,
      location: 'Centre pompidou, Paris',
      inventoryNumber: 'AM 1975-52',
    },
    {
      id: 'art3_10',
      type: 'painting',
      title: 'b.t. 10.05.2012',
      artist: 'Miriam Cahn',
      year: '2012',
      description: ["Miriam Cahn nous donne à voir des corps étranges, “moins qu’humains” au visage à demi effacé que nous hésitons à reconnaître Dans son travail, les limites entre animal et humain se confondent. “Je trouve ça toujours difficile d’identifier ce que c’est que la personne, l’humain exactement.",
        "Quand je fais des personnages, j’y pense souvent car on ne sais pas vraiment ce qu'est la peau, où est la ligne entre intérieur et extérieur. Et c’est dans ce travail que les couleurs s’imposent. “ ",
        "Le chaos du monde déséquilibré et cette perturbation prend forme dans les corps et dans ses couleurs.  Il en résulte dans les oeuvres de Miriam Cahn  une « pietà collective, étrange et sinistre ».",
      ],
      medium: 'À définir',
      dimensions: ' 84 x 70 cm',
      position: { x: -6, y: 7, z: -59 },
      rotation: { x: 0, y: 0, z: 0 },
      image: 'oeuvres/esprit/perturbation/Miriam Cahn.png',
      subtheme: 0,
      location: 'Muzeum Sztuki Nowoczesnej, Varsovie',
      inventoryNumber: '',
    },
    {
      id: 'art3_11_pint', // ID corrigé
      type: 'painting',
      title: '',
      artist: 'Jacques-André Boiffard',
      year: '1930',
      description: 'Masque de carnaval',
      medium: 'épreuve gélatino-argentique',
      dimensions: ' 22 x 28 cm',
      position: { x: -9, y: 2.5, z: -50 },
      rotation: { x: 0, y: Math.PI/2, z: 0 },
      image: 'oeuvres/esprit/perturbation/gelatino_argentique.png',
      subtheme: 0,
      location: 'Musée national d’Art Moderne, Centre pompidou, Paris',
      inventoryNumber: 'AM 1985-118 ',
    },
    {
      id: 'art3_11_a', // ID corrigé
      type: 'painting',
      title: 'Chasseurs de fictions coloniales',
      artist: 'Denilson Baniwa',
      year: '2021',
      description: 'Série Chasseurs de fictions coloniales par Denilson Baniwa ( il veut questionner le rôle des images et du savoir anthropologique dans la construction des stéréotypes, notamment sur les peuples Autochtones comme primitifs, et pour ça il colle des images de la pop culture sur les premières photos prises les premiers anthropologues en Amazonie). Denilson Baniwa est un artiste indigène actuellement basé au Brésil',
      medium: 'collage numérique, reproductions',
      dimensions: ' 80 x 60 cm',
      position: { x: 9, y: 4, z: -53 },
      rotation: { x: 0, y: -Math.PI/2, z: 0 },
      image: 'oeuvres/esprit/pov/chasseurs/chasseur1.png',
      subtheme: 1,
      location: 'collection personnel de l’artiste',
      inventoryNumber: '',
    },
    {
      id: 'art3_11_b', // ID corrigé
      type: 'painting',
      title: 'Chasseurs de fictions coloniales',
      artist: 'Denilson Baniwa',
      year: '2021',
      description: 'Série Chasseurs de fictions coloniales par Denilson Baniwa ( il veut questionner le rôle des images et du savoir anthropologique dans la construction des stéréotypes, notamment sur les peuples Autochtones comme primitifs, et pour ça il colle des images de la pop culture sur les premières photos prises les premiers anthropologues en Amazonie). Denilson Baniwa est un artiste indigène actuellement basé au Brésil',
      medium: 'collage numérique, reproductions',
      dimensions: ' 80 x 60 cm',
      position: { x: 9, y: 4, z: -49 },
      rotation: { x: 0, y: -Math.PI/2, z: 0 },
      image: 'oeuvres/esprit/pov/chasseurs/chasseur2.png',
      subtheme: 1,
      location: 'collection personnel de l’artiste',
      inventoryNumber: '',
    },
    {
      id: 'art3_11_c', // ID corrigé
      type: 'painting',
      title: 'Chasseurs de fictions coloniales',
      artist: 'Denilson Baniwa',
      year: '2021',
      descriptionSlides: ["Cartel Enfant : As-tu déjà vu Star Wars ? Si oui tu as forcément dû reconnaître R2D2 sur la photo. Que fait-il dans ce décor, ça c’est une bonne question. L’artiste qui a réalisé cette série de photographie s’appelle Denilson Baniwa et est un artiste indigène brésilien. Indigène signifie qu’il fait partie d’une population, les Baniwa, qui était présente au Brésil avant l’arrivée des Européens.",
        "L’artiste prend des photos d’époque, datant généralement du XIXe siècle, et ajoute des éléments de notre culture dessus. Il fait ça pour inviter les gens à réfléchir sur l’utilisation des images pour faire connaître les peuples indigènes. En effet, certaines de ces images représentaient des clichés, ce qui a conduit aux développements de stéréotypes sur les populations indigènes. "
      ],
      hasChildLabel: true,
      medium: 'collage numérique, reproductions',
      dimensions: ' 60 x 80 cm',
      position: { x: 9, y: 4, z: -46 },
      rotation: { x: 0, y: -Math.PI/2, z: 0 },
      image: 'oeuvres/esprit/pov/chasseurs/chasseur3.png',
      subtheme: 1,
      location: 'collection personnel de l’artiste',
      inventoryNumber: '',
    },
    {
      id: 'art3_12',
      type: 'painting',
      title: 'Untitled',
      artist: 'Emily Kame Kngwarreye',
      year: '1994',
      descriptionSlides: ["Emily Kame Kngwarreye est une figure emblématique de l’art aborigène contemporain, mélangeant traditions ancestrales de son peuple Anmatyerr et expression artistiques modernes comme l’abstraction. Sa formation artistique est d’abord et avant tout traditionnelle et culturelle pour préserver l'héritage ancestral des dessins et des motifs laissés dans le paysage car la terre est une toile sur laquelle s’inscrit la trace des activités ancestrales, selon la plupart des cultures aborigènes australiennes. ",
        "Évoquer l’esprit en déséquilibre permet d’aborder la question d’un point de vue autre, décalé par rapport à une culture occidentale dominante et de mettre en valeur ces cultures invisibilisées. "
      ],
      medium: 'acrylique sur toile',
      dimensions: ' 80 x 80 cm',
      position: { x: 5, y: 4, z: -55 },
      rotation: { x: 0, y: 0, z: 0 },
      image: 'oeuvres/esprit/pov/untilted.png',
      subtheme: 1,
      location: 'musée du quai Branly, Paris',
      inventoryNumber: '70.2010.14.1',
    },
    {
      id: 'art3_13',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/kafigeledio.glb',
      title: 'statue anthropomorphe kafigueledio',
      artist: 'Inconnu',
      year: 'XIXe - première moitié du XXe siècle',
      description: 'Cartel Enfant : Regarde cette statue. Dis-moi arrives-tu à savoir ce qui fait qu’elle est spéciale ? C’est une statue qu’on appelle kafigueledio, ce qui veut dire « celui qui dit la vérité». Cette statue est une statue de divination ! Elle a été fabriquée par le peuple sénoufo, un peuple vivant en Afrique de l’Ouest, surtout dans le pays qui est aujourd’hui la Côte d’Ivoire. Aimerais-tu pouvoir connaître le futur ?',
      hasChildLabel:true,
      medium: 'bois, tissu, plumes, poils, cauris, matières composites',
      dimensions: '68 x 26 x 26cm',
      position: { x: 5, y: 1, z: - 51},
      rotation: { x: 0, y: -Math.PI/2, z: 0 },
      subtheme: 2,
      location: 'musée du quai Branly, Paris',
      inventoryNumber: '70.2011.28.1',
      image: 'oeuvres/esprit/esprits/kafigeledio_scul.png'

    },
    {
      id: 'art3_14',
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/nkisi.glb',
      title: 'Statue magique nkisi',
      artist: 'Inconnu',
      year: 'avant 1931',
      description: '',
      medium: 'bois, métal, plumes, pigments, matières organiques',
      dimensions: '73 x 20 x 21cm',
      position: { x: 5, y: 1, z: - 48},
      rotation: { x: 0, y: -Math.PI/2, z: 0 },
      subtheme: 2,
      location: 'musée du quai Branly, Paris',
      inventoryNumber: '71.1931.87.13',
      image: 'oeuvres/esprit/esprits/nkisi_scul.png',
    },
    {
      id: 'art3_15_glb', // ID corrigé
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/serpent.glb',
      title: 'Spatule vomitive en forme de serpent',
      artist: 'Inconnu',
      year: '1300-1500,',
      description: '',
      medium: 'bois',
      dimensions: '22 x 13 x 5cm',
      position: { x: 4, y: 1, z: - 43},
      rotation: { x: 0, y: -Math.PI/2, z: 0 },
      subtheme: 2,
      location: 'musée du quai Branly, Paris',
      inventoryNumber: '70.2009.47.1',
      image: 'oeuvres/esprit/esprits/serpent.png'
    },
    {
      id: 'art3_16_glb', // ID corrigé
      type: 'glb',
      url: 'https://wktlnqvfxf7srwv7.public.blob.vercel-storage.com/tabata.glb',
      title: 'Sculpture Tabataba',
      artist: 'Inconnu',
      year: 'fin du XIXe siècle',
      description: 'Cette sculpture a été fabriquée par le peuple Tolaï qui vit en Papouasie-Nouvelle-Guinée. Le processus de fabrication de ce type de sculpture est tenu secret, probablement parce que cette sculpture servait dans des rituels de la société secrète initiatique Iniet, réservée aux hommes. Différentes formes d’art étaient utilisées pour représenter les esprits, dont la sculpture. Les magies au sein de la société secrète étaient réalisées pour recevoir les pouvoirs des esprits. Cette sculpture témoigne d’une culture qui communique avec les esprits, ce qui lui donne une vision autre du monde qui nous entoure. ',
      medium: 'bois assemblé, fibres végétales, plumes, écaille, os, pigments',
      dimensions: '380 x 126 x 1cm',
      position: { x: -3, y: 5, z: - 41},
      rotation: { x: 0, y: Math.PI, z: 0 },
      subtheme: 2,
      location: 'musée du quai Branly, Paris',
      inventoryNumber: '72.1987.4.1',
      image: 'oeuvres/esprit/esprits/tabata_scul.png'
    }
  ]}


// --- Configuration des portes ---
export const DOORS_CONFIG = [
  {
    id: 'door_cosmos',
    targetRoom: 'room1',
    label: 'Cosmos',
    position: { x: -9.5, y: 0, z: 0 },
    rotation: { x: 0, y: Math.PI / 2, z: 0 },
    color: '#9d4edd'
    
  },
  {
    id: 'door_body',
    targetRoom: 'room2',
    label: 'Corps',
    position: { x: 9.5, y: 0, z: 0 },
    rotation: { x: 0, y: -Math.PI / 2, z: 0 },
    color: '#ff4444'
  },
  {
    id: 'door_mind',
    targetRoom: 'room3',
    label: 'Esprit',
    position: { x: 0, y: 0, z: -9.5 },
    rotation: { x: 0, y: Math.PI, z: 0 },
    color: '#4cc9f0'
  },
  // Portes de retour vers le hall
  {
    id: 'door_cosmos_back',
    targetRoom: 'room0',
    label: 'HALL',
    position: { x: -40.5, y: 0, z: 0 },
    rotation: { x: 0, y: -Math.PI / 2, z: 0 },
    color: '#4a4a6a'
  },
  {
    id: 'door_body_back',
    targetRoom: 'room0',
    label: 'HALL',
    position: { x: 40.5, y: 0, z: 0 },
    rotation: { x: 0, y: Math.PI / 2, z: 0 },
    color: '#4a4a6a'
  },
  {
    id: 'door_mind_back',
    targetRoom: 'room0',
    label: 'HALL',
    position: { x: 0, y: 0, z: -40.5 },
    rotation: { x: 0, y: 0, z: 0 },
    color: '#4a4a6a'
  }
];